using System.Runtime.InteropServices;

namespace PeriForm.Domain.Inputs.Native.Structs;

/// <summary>
/// Describes a simulated hardware input event.  Not used for keyboard/mouse.
/// Included for completeness.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
internal struct HardwareInput
{
    /// <summary>
    /// The message generated by the input hardware.
    /// </summary>
    public uint uMsg;

    /// <summary>
    /// The low‑order word of additional information.
    /// </summary>
    public ushort wParamL;

    /// <summary>
    /// The high‑order word of additional information.
    /// </summary>
    public ushort wParamH;
}
