using System.Runtime.InteropServices;

namespace PeriForm.Domain.Inputs.Native.Structs;

/// <summary>
/// Describes a simulated hardware input event for <see cref="Input"/>.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
internal struct HardwareInput
{
    /// <summary>
    /// The message generated by the input hardware.
    /// </summary>
    public uint Msg;

    /// <summary>
    /// The low‑order word of additional information.
    /// </summary>
    public ushort ParamL;

    /// <summary>
    /// The high‑order word of additional information.
    /// </summary>
    public ushort ParamH;
}
